FrameworkZ = FrameworkZ or {}
FrameworkZ.Enumerations = FrameworkZ.Enumerations or {}

FZ_ALIGN_CENTER = "center"
FZ_ALIGN_LEFT = "left"
FZ_ALIGN_RIGHT = "right"

FZ_FONT_TITLE = "Title"
FZ_FONT_LARGE = "Large"
FZ_FONT_MEDIUM = "Medium"
FZ_FONT_SMALL = "Small"

FZ_ENUM_CHARACTER_INFO_AGE = "Age"
FZ_ENUM_CHARACTER_INFO_BEARD_COLOR = "BeardColor"
FZ_ENUM_CHARACTER_INFO_BEARD_STYLE = "BeardStyle"
FZ_ENUM_CHARACTER_INFO_DESCRIPTION = "Description"
FZ_ENUM_CHARACTER_INFO_EYE_COLOR = "EyeColor"
FZ_ENUM_CHARACTER_INFO_FACTION = "Faction"
FZ_ENUM_CHARACTER_INFO_GENDER = "Gender"
FZ_ENUM_CHARACTER_INFO_HAIR_COLOR = "HairColor"
FZ_ENUM_CHARACTER_INFO_HAIR_STYLE = "HairStyle"
FZ_ENUM_CHARACTER_INFO_HEIGHT = "Height"
FZ_ENUM_CHARACTER_INFO_NAME = "Name"
FZ_ENUM_CHARACTER_INFO_PHYSIQUE = "Physique"
FZ_ENUM_CHARACTER_INFO_SKIN_COLOR = "SkinColor"
FZ_ENUM_CHARACTER_INFO_WEIGHT = "Weight"
FZ_ENUM_CHARACTER_INFO_EQUIPMENT = "Equipment"

FZ_ENUM_CHARACTER_INVENTORY_LOGICAL = "InventoryLogical"
FZ_ENUM_CHARACTER_INVENTORY_PHYSICAL = "InventoryPhysical"

FZ_ENUM_CHARACTER_META_FIRST_LOAD = "FirstLoad"
FZ_ENUM_CHARACTER_META_ID = "ID"
FZ_ENUM_CHARACTER_META_RECOGNIZES = "Recognizes"
FZ_ENUM_CHARACTER_META_UID = "UID"

FZ_ENUM_EQUIPMENT_SLOT_AMMO_STRAP = "AmmoStrap"
FZ_ENUM_EQUIPMENT_SLOT_BACK = "Back"
FZ_ENUM_EQUIPMENT_SLOT_BANDAGE = "Bandage"
FZ_ENUM_EQUIPMENT_SLOT_BATH_ROBE = "BathRobe"
FZ_ENUM_EQUIPMENT_SLOT_BELLY_BUTTON = "BellyButton"
FZ_ENUM_EQUIPMENT_SLOT_BELT = "Belt"
FZ_ENUM_EQUIPMENT_SLOT_BELT_EXTRA = "BeltExtra"
FZ_ENUM_EQUIPMENT_SLOT_BOILDER_SUIT = "Boilersuit"
FZ_ENUM_EQUIPMENT_SLOT_DRESS = "Dress"
FZ_ENUM_EQUIPMENT_SLOT_EAR_TOP = "EarTop"
FZ_ENUM_EQUIPMENT_SLOT_EARS = "Ears"
FZ_ENUM_EQUIPMENT_SLOT_EYES = "Eyes"
FZ_ENUM_EQUIPMENT_SLOT_FANNY_PACK_BACK = "FannyPackBack"
FZ_ENUM_EQUIPMENT_SLOT_FANNY_PACK_FRONT = "FannyPackFront"
FZ_ENUM_EQUIPMENT_SLOT_FULL_HAT = "FullHat"
FZ_ENUM_EQUIPMENT_SLOT_FULL_SUIT = "FullSuit"
FZ_ENUM_EQUIPMENT_SLOT_FULL_SUIT_HEAD = "FullSuitHead"
FZ_ENUM_EQUIPMENT_SLOT_FULL_TOP = "FullTop"
FZ_ENUM_EQUIPMENT_SLOT_HANDS = "Hands"
FZ_ENUM_EQUIPMENT_SLOT_HANDS_LEFT = "HandsLeft"
FZ_ENUM_EQUIPMENT_SLOT_HANDS_RIGHT = "HandsRight"
FZ_ENUM_EQUIPMENT_SLOT_HAT = "Hat"
FZ_ENUM_EQUIPMENT_SLOT_JACKET = "Jacket"
FZ_ENUM_EQUIPMENT_SLOT_JACKET_BULKY = "Jacket_Bulky"
FZ_ENUM_EQUIPMENT_SLOT_JACKET_DOWN = "Jacket_Down"
FZ_ENUM_EQUIPMENT_SLOT_JACKET_HAT = "JacketHat"
FZ_ENUM_EQUIPMENT_SLOT_JACKET_HAT_BULKY = "JacketHat_Bulky"
FZ_ENUM_EQUIPMENT_SLOT_JACKET_SUIT = "JacketSuit"
FZ_ENUM_EQUIPMENT_SLOT_LEFT_EYE = "LeftEye"
FZ_ENUM_EQUIPMENT_SLOT_LEFT_MIDDLE_FINGER = "Left_MiddleFinger"
FZ_ENUM_EQUIPMENT_SLOT_LEFT_RING_FINGER = "Left_RingFinger"
FZ_ENUM_EQUIPMENT_SLOT_LEFT_WRIST = "LeftWrist"
FZ_ENUM_EQUIPMENT_SLOT_LEGS1 = "Legs1"
FZ_ENUM_EQUIPMENT_SLOT_LEGS5 = "Legs5"
FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_EYES = "MakeUp_Eyes"
FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_EYES_SHADOW = "MakeUp_EyesShadow"
FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_FULL_FACE = "MakeUp_FullFace"
FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_LIPS = "MakeUp_Lips"
FZ_ENUM_EQUIPMENT_SLOT_MASK = "Mask"
FZ_ENUM_EQUIPMENT_SLOT_MASK_EYES = "MaskEyes"
FZ_ENUM_EQUIPMENT_SLOT_MASK_FULL = "MaskFull"
FZ_ENUM_EQUIPMENT_SLOT_NECKLACE = "Necklace"
FZ_ENUM_EQUIPMENT_SLOT_NECKLACE_LONG = "Necklace_Long"
FZ_ENUM_EQUIPMENT_SLOT_NECK = "Neck"
FZ_ENUM_EQUIPMENT_SLOT_NOSE = "Nose"
FZ_ENUM_EQUIPMENT_SLOT_PANTS = "Pants"
FZ_ENUM_EQUIPMENT_SLOT_RIGHT_EYE = "RightEye"
FZ_ENUM_EQUIPMENT_SLOT_RIGHT_MIDDLE_FINGER = "Right_MiddleFinger"
FZ_ENUM_EQUIPMENT_SLOT_RIGHT_RING_FINGER = "Right_RingFinger"
FZ_ENUM_EQUIPMENT_SLOT_RIGHT_WRIST = "RightWrist"
FZ_ENUM_EQUIPMENT_SLOT_SCARF = "Scarf"
FZ_ENUM_EQUIPMENT_SLOT_SHIRT = "Shirt"
FZ_ENUM_EQUIPMENT_SLOT_SHOES = "Shoes"
FZ_ENUM_EQUIPMENT_SLOT_SHORT_SLEEVE_SHIRT = "ShortSleeveShirt"
FZ_ENUM_EQUIPMENT_SLOT_SKIRT = "Skirt"
FZ_ENUM_EQUIPMENT_SLOT_SOCKS = "Socks"
FZ_ENUM_EQUIPMENT_SLOT_SWEATER = "Sweater"
FZ_ENUM_EQUIPMENT_SLOT_SWEATER_HAT = "SweaterHat"
FZ_ENUM_EQUIPMENT_SLOT_TAIL = "Tail"
FZ_ENUM_EQUIPMENT_SLOT_TANK_TOP = "TankTop"
FZ_ENUM_EQUIPMENT_SLOT_TORSO1 = "Torso1"
FZ_ENUM_EQUIPMENT_SLOT_TORSO_EXTRA = "TorsoExtra"
FZ_ENUM_EQUIPMENT_SLOT_TORSO_EXTRA_VEST = "TorsoExtraVest"
FZ_ENUM_EQUIPMENT_SLOT_TORSO_LEGS1 = "Torso1Legs1"
FZ_ENUM_EQUIPMENT_SLOT_TSHIRT = "Tshirt"
FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR = "Underwear"
FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_BOTTOM = "UnderwearBottom"
FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_EXTRA1 = "UnderwearExtra1"
FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_EXTRA2 = "UnderwearExtra2"
FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_TOP = "UnderwearTop"
FZ_ENUM_EQUIPMENT_SLOT_WOUND = "Wound"
FZ_ENUM_EQUIPMENT_SLOT_ZED_DMG = "ZedDmg"

FrameworkZ.Enumerations.EquipmentSlots = {
    FZ_ENUM_EQUIPMENT_SLOT_AMMO_STRAP,
    FZ_ENUM_EQUIPMENT_SLOT_BACK,
    FZ_ENUM_EQUIPMENT_SLOT_BANDAGE,
    FZ_ENUM_EQUIPMENT_SLOT_BATH_ROBE,
    FZ_ENUM_EQUIPMENT_SLOT_BELLY_BUTTON,
    FZ_ENUM_EQUIPMENT_SLOT_BELT,
    FZ_ENUM_EQUIPMENT_SLOT_BELT_EXTRA,
    FZ_ENUM_EQUIPMENT_SLOT_BOILDER_SUIT,
    FZ_ENUM_EQUIPMENT_SLOT_DRESS,
    FZ_ENUM_EQUIPMENT_SLOT_EAR_TOP,
    FZ_ENUM_EQUIPMENT_SLOT_EARS,
    FZ_ENUM_EQUIPMENT_SLOT_EYES,
    FZ_ENUM_EQUIPMENT_SLOT_FANNY_PACK_BACK,
    FZ_ENUM_EQUIPMENT_SLOT_FANNY_PACK_FRONT,
    FZ_ENUM_EQUIPMENT_SLOT_FULL_HAT,
    FZ_ENUM_EQUIPMENT_SLOT_FULL_SUIT,
    FZ_ENUM_EQUIPMENT_SLOT_FULL_SUIT_HEAD,
    FZ_ENUM_EQUIPMENT_SLOT_FULL_TOP,
    FZ_ENUM_EQUIPMENT_SLOT_HANDS,
    FZ_ENUM_EQUIPMENT_SLOT_HANDS_LEFT,
    FZ_ENUM_EQUIPMENT_SLOT_HANDS_RIGHT,
    FZ_ENUM_EQUIPMENT_SLOT_HAT,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET_BULKY,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET_DOWN,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET_HAT,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET_HAT_BULKY,
    FZ_ENUM_EQUIPMENT_SLOT_JACKET_SUIT,
    FZ_ENUM_EQUIPMENT_SLOT_LEFT_EYE,
    FZ_ENUM_EQUIPMENT_SLOT_LEFT_MIDDLE_FINGER,
    FZ_ENUM_EQUIPMENT_SLOT_LEFT_RING_FINGER,
    FZ_ENUM_EQUIPMENT_SLOT_LEFT_WRIST,
    FZ_ENUM_EQUIPMENT_SLOT_LEGS1,
    FZ_ENUM_EQUIPMENT_SLOT_LEGS5,
    FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_EYES,
    FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_EYES_SHADOW,
    FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_FULL_FACE,
    FZ_ENUM_EQUIPMENT_SLOT_MAKEUP_LIPS,
    FZ_ENUM_EQUIPMENT_SLOT_MASK,
    FZ_ENUM_EQUIPMENT_SLOT_MASK_EYES,
    FZ_ENUM_EQUIPMENT_SLOT_MASK_FULL,
    FZ_ENUM_EQUIPMENT_SLOT_NECKLACE,
    FZ_ENUM_EQUIPMENT_SLOT_NECKLACE_LONG,
    FZ_ENUM_EQUIPMENT_SLOT_NECK,
    FZ_ENUM_EQUIPMENT_SLOT_NOSE,
    FZ_ENUM_EQUIPMENT_SLOT_PANTS,
    FZ_ENUM_EQUIPMENT_SLOT_RIGHT_EYE,
    FZ_ENUM_EQUIPMENT_SLOT_RIGHT_MIDDLE_FINGER,
    FZ_ENUM_EQUIPMENT_SLOT_RIGHT_RING_FINGER,
    FZ_ENUM_EQUIPMENT_SLOT_RIGHT_WRIST,
    FZ_ENUM_EQUIPMENT_SLOT_SCARF,
    FZ_ENUM_EQUIPMENT_SLOT_SHIRT,
    FZ_ENUM_EQUIPMENT_SLOT_SHOES,
    FZ_ENUM_EQUIPMENT_SLOT_SHORT_SLEEVE_SHIRT,
    FZ_ENUM_EQUIPMENT_SLOT_SKIRT,
    FZ_ENUM_EQUIPMENT_SLOT_SOCKS,
    FZ_ENUM_EQUIPMENT_SLOT_SWEATER,
    FZ_ENUM_EQUIPMENT_SLOT_SWEATER_HAT,
    FZ_ENUM_EQUIPMENT_SLOT_TAIL,
    FZ_ENUM_EQUIPMENT_SLOT_TANK_TOP,
    FZ_ENUM_EQUIPMENT_SLOT_TORSO1,
    FZ_ENUM_EQUIPMENT_SLOT_TORSO_EXTRA,
    FZ_ENUM_EQUIPMENT_SLOT_TORSO_EXTRA_VEST,
    FZ_ENUM_EQUIPMENT_SLOT_TORSO_LEGS1,
    FZ_ENUM_EQUIPMENT_SLOT_TSHIRT,
    FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR,
    FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_BOTTOM,
    FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_EXTRA1,
    FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_EXTRA2,
    FZ_ENUM_EQUIPMENT_SLOT_UNDERWEAR_TOP,
    FZ_ENUM_EQUIPMENT_SLOT_WOUND,
    FZ_ENUM_EQUIPMENT_SLOT_ZED_DMG
}